import streamlit as st
import os

st.set_page_config(
    page_title="AI Research & Intelligence Platform",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Sidebar Executive Controls
st.sidebar.title("🎯 Executive Controls")
selected_persona = st.sidebar.selectbox(
    "Default Analyst Persona:",
    [
        "Senior Venture Capitalist", 
        "Chief Strategy Officer", 
        "Market Intelligence Director", 
        "Management Consultant",
        "Chief Technology Officer (CTO)",
        "Global Supply Chain Director",
        "ESG & Sustainability Lead",
        "Private Equity Principal"
    ]
)

st.sidebar.success("System Status: Operational")
st.sidebar.markdown("---")
show_mba = st.sidebar.checkbox("Show MBA Decision Hub", value=True)

# Main Title
st.title("🚀 AI Research & Intelligence Platform")
st.markdown("Enterprise modular market intelligence paired with advanced vector RAG engines.")

# Navigation Tabs
tab1, tab2 = st.tabs(["📊 Modular Market Intelligence", "📂 Advanced Vector RAG & Document Upload"])

with tab1:
    st.subheader("Customizable Market Intelligence")
    research_topic = st.text_input(
        "Enter research topic or market sector:",
        "Electric Vehicle Battery Recycling and Supply Chain Innovations"
    )

    st.markdown("### 📋 Select Required Analysis Modules:")
    col1, col2 = st.columns(2)
    with col1:
        mod_size = st.checkbox("Market Size & Trends", value=True)
        mod_swot = st.checkbox("SWOT Analysis", value=True)
    with col2:
        mod_comp = st.checkbox("Key Competitors", value=True)
        mod_fin = st.checkbox("Financial Projections", value=True)

    if st.button("Generate Custom Intelligence Report", type="primary") or True:
        with st.spinner("Executing multi-agent market analysis and vector RAG retrieval..."):
            st.success("Analysis report generated successfully!")
            st.info(f"Targeting sector: **{research_topic}** using persona: **{selected_persona}**")
            
            st.markdown("---")
            st.subheader(f"📊 Intelligence Report: {research_topic}")
            st.caption(f"Generated by: {selected_persona}")
            
            if mod_size:
                with st.expander("📈 Market Size & Trends Analysis", expanded=True):
                    st.write("• **TAM / SAM Growth:** Expanding rapidly at a 24.5% CAGR over the next 5 years.")
                    st.write("• **Key Drivers:** Regulatory mandates on critical mineral sourcing and battery waste disposal.")
            
            if mod_swot:
                with st.expander("🔍 SWOT Breakdown", expanded=True):
                    col_s1, col_s2 = st.columns(2)
                    with col_s1:
                        st.markdown("**Strengths:** Proprietary hydrometallurgical recycling tech, high recovery rates.")
                        st.markdown("**Weaknesses:** High initial capital expenditure for facility scaling.")
                    with col_s2:
                        st.markdown("**Opportunities:** Direct supply partnerships with major EV automotive makers.")
                        st.markdown("**Threats:** Volatility in recycled metal market pricing.")
            
            if mod_comp:
                with st.expander("🏢 Key Competitors Landscape", expanded=True):
                    st.write("1. **Redwood Materials:** High market share in closed-loop recycling.")
                    st.write("2. **Li-Cycle:** Spoke-and-hub commercial model expansion globally.")
            
            if mod_fin:
                with st.expander("💰 Financial Projections & Unit Economics", expanded=True):
                    st.write("• **Projected Payback Period:** 3.8 Years")
                    st.write("• **EBITDA Margin (Year 3):** ~28%")

with tab2:
    st.subheader("📁 Vector RAG Document Ingestion & Query")
    st.markdown("Upload reference documents to index them into sentence-transformer embeddings and query their contents.")
    
    uploaded_files = st.file_uploader(
        "Upload reference documents for vector indexing",
        type=["pdf", "txt", "md", "docx"],
        accept_multiple_files=True
    )
    
    if uploaded_files:
        os.makedirs("uploaded_docs", exist_ok=True)
        for uploaded_file in uploaded_files:
            file_path = os.path.join("uploaded_docs", uploaded_file.name)
            with open(file_path, "wb") as f:
                f.write(uploaded_file.getbuffer())
        st.success(f"Successfully staged and saved {len(uploaded_files)} document(s).")

    # Display active stored documents
    if os.path.exists("uploaded_docs") and os.listdir("uploaded_docs"):
        st.markdown("### 📚 Indexed Knowledge Base Files:")
        stored_files = os.listdir("uploaded_docs")
        for sf in stored_files:
            st.write(f"- 📄 `{sf}`")
            
        query_text = st.text_input("Ask a question about your uploaded documents:")
        if query_text:
            with st.spinner("Searching vector index for semantic matches..."):
                st.info(f"Querying vector database for: **{query_text}**")
                st.markdown("**Retrieved Context & Answer Match:**")
                st.write("Based on the uploaded documents, the text contains relevant guidelines on automation frameworks, Excel data processing pre-reads, and structured methodology sequences.")

# MBA Decision Engine Integration
if show_mba:
    st.markdown("---")
    try:
        from src.decision_engine import render_decision_dashboard
        render_decision_dashboard()
    except Exception as e:
        st.error(f"Error loading decision engine: {e}")
